services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: DocuMind
    ports:
      - "5432:5432"
    networks:
      - documind
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d DocuMind" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  zoo2:
    image: confluentinc/cp-zookeeper:7.3.2
    hostname: zoo2
    container_name: zoo2
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_SERVERS: zoo2:2888:3888
    healthcheck:
      test: [ "CMD", "bash", "-c", "echo ruok | nc localhost 2181 | grep imok" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - documind


  kafkabroker:
    image: confluentinc/cp-kafka:7.3.2
    hostname: kafkabroker
    container_name: kafkabroker
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafkabroker:19092,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092,DOCKER://host.docker.internal:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,DOCKER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zoo2:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    depends_on:
      - zoo2
    healthcheck:
      test: [ "CMD", "bash", "-c", "echo > /dev/tcp/localhost/9092" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - documind

  user-service:
    image: "sundeep2205/user-service:v1"
    container_name: "user-service-ms"
    ports:
      - "8081:8081"
    deploy:
      resources:
        limits:
          memory: "1024m"
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8081/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/DocuMind
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
    networks:
      - documind


  document-service:
    image: "sundeep2205/document-service:v1"
    container_name: "document-service-ms"
    ports:
      - "8082:8082"
    deploy:
      resources:
        limits:
          memory: "1024m"
    depends_on:
      kafkabroker:
        condition: service_healthy
      postgres:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8082/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/DocuMind
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafkabroker:19092
      SPRING_KAFKA_PRODUCER_BOOTSTRAP_SERVERS: kafkabroker:19092
      SPRING_KAFKA_CONSUMER_BOOTSTRAP_SERVERS: kafkabroker:19092
      USER_SERVICE_URL: http://user-service:8081
    volumes:
      - ./uploads:/uploads
    networks:
      - documind

networks:
  documind:
    driver: bridge






